const SERVICE_TYPES = {
  PIPE_REPAIR: 'PIPE_REPAIR',
  DRAIN_CLEANING: 'DRAIN_CLEANING',
  WATER_HEATER: 'WATER_HEATER',
  INSTALLATION: 'INSTALLATION',
  LEAK_DETECTION: 'LEAK_DETECTION',
  EMERGENCY: 'EMERGENCY'
};

module.exports = {
  SERVICE_TYPES
}; 